// Code generated by protoc-gen-go. DO NOT EDIT.
// source: faultinjector.proto

package faultinjector

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EnumerateServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumerateServicesRequest) Reset()         { *m = EnumerateServicesRequest{} }
func (m *EnumerateServicesRequest) String() string { return proto.CompactTextString(m) }
func (*EnumerateServicesRequest) ProtoMessage()    {}
func (*EnumerateServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{0}
}

func (m *EnumerateServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerateServicesRequest.Unmarshal(m, b)
}
func (m *EnumerateServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerateServicesRequest.Marshal(b, m, deterministic)
}
func (m *EnumerateServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerateServicesRequest.Merge(m, src)
}
func (m *EnumerateServicesRequest) XXX_Size() int {
	return xxx_messageInfo_EnumerateServicesRequest.Size(m)
}
func (m *EnumerateServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerateServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerateServicesRequest proto.InternalMessageInfo

type EnumerateServicesResponse struct {
	Services             []*Service `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *EnumerateServicesResponse) Reset()         { *m = EnumerateServicesResponse{} }
func (m *EnumerateServicesResponse) String() string { return proto.CompactTextString(m) }
func (*EnumerateServicesResponse) ProtoMessage()    {}
func (*EnumerateServicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{1}
}

func (m *EnumerateServicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumerateServicesResponse.Unmarshal(m, b)
}
func (m *EnumerateServicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumerateServicesResponse.Marshal(b, m, deterministic)
}
func (m *EnumerateServicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumerateServicesResponse.Merge(m, src)
}
func (m *EnumerateServicesResponse) XXX_Size() int {
	return xxx_messageInfo_EnumerateServicesResponse.Size(m)
}
func (m *EnumerateServicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumerateServicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnumerateServicesResponse proto.InternalMessageInfo

func (m *EnumerateServicesResponse) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type Service struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Methods              []*Method `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{2}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetMethods() []*Method {
	if m != nil {
		return m.Methods
	}
	return nil
}

type Method struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expression           string   `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Method) Reset()         { *m = Method{} }
func (m *Method) String() string { return proto.CompactTextString(m) }
func (*Method) ProtoMessage()    {}
func (*Method) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{3}
}

func (m *Method) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Method.Unmarshal(m, b)
}
func (m *Method) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Method.Marshal(b, m, deterministic)
}
func (m *Method) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Method.Merge(m, src)
}
func (m *Method) XXX_Size() int {
	return xxx_messageInfo_Method.Size(m)
}
func (m *Method) XXX_DiscardUnknown() {
	xxx_messageInfo_Method.DiscardUnknown(m)
}

var xxx_messageInfo_Method proto.InternalMessageInfo

func (m *Method) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Method) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type RegisterFaultRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Expression           string   `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterFaultRequest) Reset()         { *m = RegisterFaultRequest{} }
func (m *RegisterFaultRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterFaultRequest) ProtoMessage()    {}
func (*RegisterFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{4}
}

func (m *RegisterFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFaultRequest.Unmarshal(m, b)
}
func (m *RegisterFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFaultRequest.Marshal(b, m, deterministic)
}
func (m *RegisterFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFaultRequest.Merge(m, src)
}
func (m *RegisterFaultRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterFaultRequest.Size(m)
}
func (m *RegisterFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFaultRequest proto.InternalMessageInfo

func (m *RegisterFaultRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RegisterFaultRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RegisterFaultRequest) GetExpression() string {
	if m != nil {
		return m.Expression
	}
	return ""
}

type RegisterFaultResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterFaultResponse) Reset()         { *m = RegisterFaultResponse{} }
func (m *RegisterFaultResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterFaultResponse) ProtoMessage()    {}
func (*RegisterFaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{5}
}

func (m *RegisterFaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterFaultResponse.Unmarshal(m, b)
}
func (m *RegisterFaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterFaultResponse.Marshal(b, m, deterministic)
}
func (m *RegisterFaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterFaultResponse.Merge(m, src)
}
func (m *RegisterFaultResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterFaultResponse.Size(m)
}
func (m *RegisterFaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterFaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterFaultResponse proto.InternalMessageInfo

type RemoveFaultRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFaultRequest) Reset()         { *m = RemoveFaultRequest{} }
func (m *RemoveFaultRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFaultRequest) ProtoMessage()    {}
func (*RemoveFaultRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{6}
}

func (m *RemoveFaultRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFaultRequest.Unmarshal(m, b)
}
func (m *RemoveFaultRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFaultRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFaultRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFaultRequest.Merge(m, src)
}
func (m *RemoveFaultRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFaultRequest.Size(m)
}
func (m *RemoveFaultRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFaultRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFaultRequest proto.InternalMessageInfo

func (m *RemoveFaultRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RemoveFaultRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

type RemoveFaultResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFaultResponse) Reset()         { *m = RemoveFaultResponse{} }
func (m *RemoveFaultResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveFaultResponse) ProtoMessage()    {}
func (*RemoveFaultResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_68264f678b457db3, []int{7}
}

func (m *RemoveFaultResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFaultResponse.Unmarshal(m, b)
}
func (m *RemoveFaultResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFaultResponse.Marshal(b, m, deterministic)
}
func (m *RemoveFaultResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFaultResponse.Merge(m, src)
}
func (m *RemoveFaultResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveFaultResponse.Size(m)
}
func (m *RemoveFaultResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFaultResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFaultResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EnumerateServicesRequest)(nil), "faultinjector.EnumerateServicesRequest")
	proto.RegisterType((*EnumerateServicesResponse)(nil), "faultinjector.EnumerateServicesResponse")
	proto.RegisterType((*Service)(nil), "faultinjector.Service")
	proto.RegisterType((*Method)(nil), "faultinjector.Method")
	proto.RegisterType((*RegisterFaultRequest)(nil), "faultinjector.RegisterFaultRequest")
	proto.RegisterType((*RegisterFaultResponse)(nil), "faultinjector.RegisterFaultResponse")
	proto.RegisterType((*RemoveFaultRequest)(nil), "faultinjector.RemoveFaultRequest")
	proto.RegisterType((*RemoveFaultResponse)(nil), "faultinjector.RemoveFaultResponse")
}

func init() {
	proto.RegisterFile("faultinjector.proto", fileDescriptor_68264f678b457db3)
}

var fileDescriptor_68264f678b457db3 = []byte{
	// 329 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xfd, 0x80, 0x2f, 0xa0, 0x43, 0x88, 0x71, 0x10, 0x5c, 0x7b, 0x30, 0xb8, 0x9a, 0xc8, 0x09,
	0x13, 0xbc, 0x7a, 0x32, 0x91, 0xc4, 0x83, 0x9a, 0xac, 0x89, 0x07, 0xe3, 0x05, 0x71, 0x94, 0x1a,
	0xdb, 0xad, 0xbb, 0x5b, 0xe2, 0xbf, 0xf2, 0x2f, 0x1a, 0xb7, 0x5b, 0x42, 0xb7, 0x15, 0x0f, 0xde,
	0xba, 0x6f, 0xde, 0xbc, 0xb7, 0xf3, 0xba, 0x03, 0xdd, 0xe7, 0x69, 0xfa, 0x66, 0xc2, 0xf8, 0x95,
	0x66, 0x46, 0xaa, 0x51, 0xa2, 0xa4, 0x91, 0xd8, 0x29, 0x80, 0x3c, 0x00, 0x76, 0x11, 0xa7, 0x11,
	0xa9, 0xa9, 0xa1, 0x5b, 0x52, 0x8b, 0x70, 0x46, 0x5a, 0xd0, 0x7b, 0x4a, 0xda, 0xf0, 0x1b, 0xd8,
	0xab, 0xa8, 0xe9, 0x44, 0xc6, 0x9a, 0x70, 0x0c, 0x1b, 0xda, 0x61, 0xac, 0x36, 0x68, 0x0c, 0xdb,
	0xe3, 0xfe, 0xa8, 0xe8, 0xe7, 0x5a, 0xc4, 0x92, 0xc7, 0xaf, 0xa1, 0xe5, 0x40, 0x44, 0xf8, 0x1f,
	0x4f, 0x23, 0x62, 0xb5, 0x41, 0x6d, 0xb8, 0x29, 0xec, 0x37, 0x9e, 0x40, 0x2b, 0x22, 0x33, 0x97,
	0x4f, 0x9a, 0xd5, 0xad, 0x62, 0xcf, 0x53, 0xbc, 0xb2, 0x55, 0x91, 0xb3, 0xf8, 0x19, 0x34, 0x33,
	0xa8, 0x52, 0x6e, 0x1f, 0x80, 0x3e, 0x12, 0x45, 0x5a, 0x87, 0x32, 0x66, 0x75, 0x5b, 0x59, 0x41,
	0xf8, 0x1c, 0x76, 0x04, 0xbd, 0x84, 0xda, 0x90, 0x9a, 0x7c, 0xdb, 0xb8, 0xb1, 0x91, 0x41, 0xcb,
	0xdd, 0xd8, 0xc9, 0xe5, 0x47, 0xec, 0x43, 0x33, 0xb3, 0x76, 0x6a, 0xee, 0xe4, 0x39, 0x35, 0x4a,
	0x4e, 0xbb, 0xd0, 0xf3, 0x9c, 0xb2, 0x10, 0xf9, 0x04, 0x50, 0x50, 0x24, 0x17, 0xf4, 0xb7, 0x0b,
	0xf0, 0x1e, 0x74, 0x0b, 0x3a, 0x99, 0xfc, 0xf8, 0xb3, 0x0e, 0x1d, 0x8b, 0x5c, 0xba, 0x04, 0x71,
	0x0e, 0xdb, 0xa5, 0x5f, 0x8a, 0xc7, 0x5e, 0xcc, 0x3f, 0x3d, 0x88, 0x60, 0xf8, 0x3b, 0xd1, 0x0d,
	0xf6, 0x0f, 0x1f, 0xa0, 0x53, 0x98, 0x19, 0x0f, 0xbd, 0xe6, 0xaa, 0xec, 0x83, 0xa3, 0xf5, 0xa4,
	0xa5, 0xfa, 0x1d, 0xb4, 0x57, 0x06, 0xc6, 0x83, 0x52, 0x9b, 0x1f, 0x6a, 0xc0, 0xd7, 0x51, 0x72,
	0xdd, 0xf3, 0xad, 0xfb, 0xe2, 0x7e, 0x3c, 0x36, 0xed, 0xd6, 0x9c, 0x7e, 0x05, 0x00, 0x00, 0xff,
	0xff, 0x3e, 0xe6, 0xaf, 0xb2, 0x4c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FaultInjectorClient is the client API for FaultInjector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaultInjectorClient interface {
	// Sends a greeting
	EnumerateServices(ctx context.Context, in *EnumerateServicesRequest, opts ...grpc.CallOption) (*EnumerateServicesResponse, error)
	RegisterFault(ctx context.Context, in *RegisterFaultRequest, opts ...grpc.CallOption) (*RegisterFaultResponse, error)
	RemoveFault(ctx context.Context, in *RemoveFaultRequest, opts ...grpc.CallOption) (*RemoveFaultResponse, error)
}

type faultInjectorClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultInjectorClient(cc grpc.ClientConnInterface) FaultInjectorClient {
	return &faultInjectorClient{cc}
}

func (c *faultInjectorClient) EnumerateServices(ctx context.Context, in *EnumerateServicesRequest, opts ...grpc.CallOption) (*EnumerateServicesResponse, error) {
	out := new(EnumerateServicesResponse)
	err := c.cc.Invoke(ctx, "/faultinjector.FaultInjector/EnumerateServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faultInjectorClient) RegisterFault(ctx context.Context, in *RegisterFaultRequest, opts ...grpc.CallOption) (*RegisterFaultResponse, error) {
	out := new(RegisterFaultResponse)
	err := c.cc.Invoke(ctx, "/faultinjector.FaultInjector/RegisterFault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faultInjectorClient) RemoveFault(ctx context.Context, in *RemoveFaultRequest, opts ...grpc.CallOption) (*RemoveFaultResponse, error) {
	out := new(RemoveFaultResponse)
	err := c.cc.Invoke(ctx, "/faultinjector.FaultInjector/RemoveFault", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaultInjectorServer is the server API for FaultInjector service.
type FaultInjectorServer interface {
	// Sends a greeting
	EnumerateServices(context.Context, *EnumerateServicesRequest) (*EnumerateServicesResponse, error)
	RegisterFault(context.Context, *RegisterFaultRequest) (*RegisterFaultResponse, error)
	RemoveFault(context.Context, *RemoveFaultRequest) (*RemoveFaultResponse, error)
}

// UnimplementedFaultInjectorServer can be embedded to have forward compatible implementations.
type UnimplementedFaultInjectorServer struct {
}

func (*UnimplementedFaultInjectorServer) EnumerateServices(ctx context.Context, req *EnumerateServicesRequest) (*EnumerateServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumerateServices not implemented")
}
func (*UnimplementedFaultInjectorServer) RegisterFault(ctx context.Context, req *RegisterFaultRequest) (*RegisterFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterFault not implemented")
}
func (*UnimplementedFaultInjectorServer) RemoveFault(ctx context.Context, req *RemoveFaultRequest) (*RemoveFaultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFault not implemented")
}

func RegisterFaultInjectorServer(s *grpc.Server, srv FaultInjectorServer) {
	s.RegisterService(&_FaultInjector_serviceDesc, srv)
}

func _FaultInjector_EnumerateServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumerateServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultInjectorServer).EnumerateServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faultinjector.FaultInjector/EnumerateServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultInjectorServer).EnumerateServices(ctx, req.(*EnumerateServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaultInjector_RegisterFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultInjectorServer).RegisterFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faultinjector.FaultInjector/RegisterFault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultInjectorServer).RegisterFault(ctx, req.(*RegisterFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaultInjector_RemoveFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultInjectorServer).RemoveFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/faultinjector.FaultInjector/RemoveFault",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultInjectorServer).RemoveFault(ctx, req.(*RemoveFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FaultInjector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "faultinjector.FaultInjector",
	HandlerType: (*FaultInjectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnumerateServices",
			Handler:    _FaultInjector_EnumerateServices_Handler,
		},
		{
			MethodName: "RegisterFault",
			Handler:    _FaultInjector_RegisterFault_Handler,
		},
		{
			MethodName: "RemoveFault",
			Handler:    _FaultInjector_RemoveFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faultinjector.proto",
}
