// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SayHelloStreamingReply(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamingReplyClient, error)
	SayHelloStreamingRequest(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamingRequestClient, error)
	SayHelloStreamingRequestReply(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamingRequestReplyClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloStreamingReply(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloStreamingReplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/helloworld.Greeter/SayHelloStreamingReply", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamingReplyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloStreamingReplyClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamingReplyClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamingReplyClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloStreamingRequest(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamingRequestClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/helloworld.Greeter/SayHelloStreamingRequest", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamingRequestClient{stream}
	return x, nil
}

type Greeter_SayHelloStreamingRequestClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamingRequestClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamingRequestClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloStreamingRequestClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloStreamingRequestReply(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStreamingRequestReplyClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/helloworld.Greeter/SayHelloStreamingRequestReply", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStreamingRequestReplyClient{stream}
	return x, nil
}

type Greeter_SayHelloStreamingRequestReplyClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloStreamingRequestReplyClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStreamingRequestReplyClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloStreamingRequestReplyClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	SayHelloStreamingReply(*HelloRequest, Greeter_SayHelloStreamingReplyServer) error
	SayHelloStreamingRequest(Greeter_SayHelloStreamingRequestServer) error
	SayHelloStreamingRequestReply(Greeter_SayHelloStreamingRequestReplyServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SayHelloStreamingReply(*HelloRequest, Greeter_SayHelloStreamingReplyServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreamingReply not implemented")
}
func (UnimplementedGreeterServer) SayHelloStreamingRequest(Greeter_SayHelloStreamingRequestServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreamingRequest not implemented")
}
func (UnimplementedGreeterServer) SayHelloStreamingRequestReply(Greeter_SayHelloStreamingRequestReplyServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStreamingRequestReply not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloStreamingReply_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHelloStreamingReply(m, &greeterSayHelloStreamingReplyServer{stream})
}

type Greeter_SayHelloStreamingReplyServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHelloStreamingReplyServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamingReplyServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHelloStreamingRequest_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloStreamingRequest(&greeterSayHelloStreamingRequestServer{stream})
}

type Greeter_SayHelloStreamingRequestServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloStreamingRequestServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamingRequestServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloStreamingRequestServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_SayHelloStreamingRequestReply_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloStreamingRequestReply(&greeterSayHelloStreamingRequestReplyServer{stream})
}

type Greeter_SayHelloStreamingRequestReplyServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloStreamingRequestReplyServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStreamingRequestReplyServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloStreamingRequestReplyServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloStreamingReply",
			Handler:       _Greeter_SayHelloStreamingReply_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloStreamingRequest",
			Handler:       _Greeter_SayHelloStreamingRequest_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloStreamingRequestReply",
			Handler:       _Greeter_SayHelloStreamingRequestReply_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
